#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# generated by wxGlade 0.6.8 on Wed Jun 11 13:41:49 2014
#

from ..lib.wx_loader import wx
from wx import grid
import traceback

# begin wxGlade: dependencies
# end wxGlade

import time, math, os
from MAVProxy.modules.lib import mp_util
from MAVProxy.modules.lib import win_layout
from MAVProxy.modules.mavproxy_misseditor import me_event
MissionEditorEvent = me_event.MissionEditorEvent

from MAVProxy.modules.mavproxy_misseditor import me_defines
from MAVProxy.modules.lib import mp_elevation

from MAVProxy.modules.mavproxy_misseditor import button_renderer
from pymavlink import mavutil

#define column names via "enums":
ME_COMMAND_COL = 0
ME_P1_COL = 1
ME_P2_COL = 2
ME_P3_COL = 3
ME_P4_COL = 4
ME_LAT_COL = 5
ME_LON_COL = 6
ME_ALT_COL = 7
ME_FRAME_COL = 8
ME_DELETE_COL = 9
ME_UP_COL = 10
ME_DOWN_COL = 11
ME_DIST_COL = 12
ME_ANGLE_COL = 13
ME_AGL_COL = 14


class ListCtrlComboPopup(wx.ComboPopup):

    def __init__(self):
        wx.ComboPopup.__init__(self)
        self.lc = None

    def AddItem(self, txt):
        self.lc.InsertItem(self.lc.GetItemCount(), txt)

    def OnMotion(self, evt):
        item, flags = self.lc.HitTest(evt.GetPosition())
        if item >= 0:
            self.lc.Select(item)
            self.curitem = item

    def OnLeftDown(self, evt):
        self.value = self.curitem
        self.Dismiss()

    # This is called immediately after construction finishes.  You can
    # use self.GetCombo if needed to get to the ComboCtrl instance.
    def Init(self):
        self.value = -1
        self.curitem = -1

    # Create the popup child control.  Return true for success.
    def Create(self, parent):
        self.lc = wx.ListCtrl(parent, style=wx.LC_SINGLE_SEL | wx.SIMPLE_BORDER | wx.LC_REPORT | wx.LC_NO_HEADER)
        self.lc.InsertColumn(0, '')
        self.lc.Bind(wx.EVT_MOTION, self.OnMotion)
        self.lc.Bind(wx.EVT_LEFT_DOWN, self.OnLeftDown)
        return True

    # Return the widget that is to be used for the popup
    def GetControl(self):
        return self.lc

    # Called just prior to displaying the popup, you can use it to
    # 'select' the current item.
    def SetStringValue(self, val):
        idx = self.lc.FindItem(-1, val)
        if idx != wx.NOT_FOUND:
            self.lc.Select(idx)

    def FindString(self, val):
        idx = self.lc.FindItem(-1, val)
        if idx == wx.NOT_FOUND:
            idx = 0
        return idx

    # Return a string representation of the current item.
    def GetStringValue(self):
        if self.value >= 0:
            return self.lc.GetItemText(self.value)
        return ""

    # Called immediately after the popup is shown
    def OnPopup(self):
        self.lc.SetColumnWidth(0, wx.LIST_AUTOSIZE)
        wx.ComboPopup.OnPopup(self)

    # Called when popup is dismissed
    def OnDismiss(self):
        wx.ComboPopup.OnDismiss(self)

    # This is called to custom paint in the combo control itself
    # (ie. not the popup).  Default implementation draws value as
    # string.
    def PaintComboControl(self, dc, rect):
        wx.ComboPopup.PaintComboControl(self, dc, rect)

    # Receives key events from the parent ComboCtrl.  Events not
    # handled should be skipped, as usual.
    def OnComboKeyEvent(self, event):
        wx.ComboPopup.OnComboKeyEvent(self, event)

    # Implement if you need to support special action when user
    # double-clicks on the parent wxComboCtrl.
    def OnComboDoubleClick(self):
        wx.ComboPopup.OnComboDoubleClick(self)

    # Return final size of popup. Called on every popup, just prior to OnPopup.
    # minWidth = preferred minimum width for window
    # prefHeight = preferred height. Only applies if > 0,
    # maxHeight = max height for window, as limited by screen size
    #   and should only be rounded down, if necessary.
    def GetAdjustedSize(self, minWidth, prefHeight, maxHeight):
        return wx.ComboPopup.GetAdjustedSize(self, minWidth, prefHeight, maxHeight)

    # Return true if you want delay the call to Create until the popup
    # is shown for the first time. It is more efficient, but note that
    # it is often more convenient to have the control created
    # immediately.
    # Default returns false.
    def LazyCreate(self):
        return wx.ComboPopup.LazyCreate(self)


class DropdownCellEditor(grid.GridCellEditor):
    def __init__(self, choices):
        super().__init__()
        self.choices = choices

    def Create(self, parent, id, evtHandler):
        self.control = wx.ComboCtrl(parent, id, "", style=wx.CB_READONLY)
        self.popupCtrl = ListCtrlComboPopup()
        self.control.SetPopupControl(self.popupCtrl)
        for choice in self.choices:
            self.popupCtrl.AddItem(choice)
        self.SetControl(self.control)

    def Clone(self):
        return DropdownCellEditor(self.choices)

    def BeginEdit(self, row, col, grid):
        self.startValue = grid.GetTable().GetValue(row, col)
        self.control.SetValue(self.startValue)

    def EndEdit(self, row, col, grid, oldval):
        self.endValue = self.popupCtrl.GetStringValue()
        if self.endValue != oldval and self.endValue != "":
            return self.endValue
        else:
            return None

    def ApplyEdit(self, row, col, grid):
        self.control.SetValue(self.endValue)
        grid.GetTable().SetValue(row, col, self.endValue)

    def Reset(self):
        self.control.SetValue(self.startValue)


class MissionEditorFrame(wx.Frame):
    def __init__(self, state, elemodel='SRTM3', *args, **kwds):
        # begin wxGlade: MissionEditorFrame.__init__
        self.state = state
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_sync_state = wx.StaticText(self, wx.ID_ANY, "UNSYNCED   \n", style=wx.ALIGN_CENTRE)
        self.button_read_wps = wx.Button(self, wx.ID_ANY, "Read WPs")
        self.button_write_wps = wx.Button(self, wx.ID_ANY, "Write WPs")
        self.button_load_wp_file = wx.Button(self, wx.ID_ANY, "Load WP File")
        self.button_save_wp_file = wx.Button(self, wx.ID_ANY, "Save WP File")
        self.grid_mission = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))
        self.button_add_wp = wx.Button(self, wx.ID_ANY, "Add Below")
        self.button_split = wx.Button(self, wx.ID_ANY, "Split")
        
        # Store home location values (needed for mission operations)
        self.home_lat = 0.0
        self.home_lon = 0.0
        self.home_alt = 0.0

        self.__set_properties()
        self.__do_layout()

        self.ElevationModel = mp_elevation.ElevationModel(database=elemodel)


        self.Bind(wx.EVT_BUTTON, self.read_wp_pushed, self.button_read_wps)
        self.Bind(wx.EVT_BUTTON, self.write_wp_pushed, self.button_write_wps)
        self.Bind(wx.EVT_BUTTON, self.load_wp_file_pushed, self.button_load_wp_file)
        self.Bind(wx.EVT_BUTTON, self.save_wp_file_pushed, self.button_save_wp_file)
        self.Bind(wx.grid.EVT_GRID_CMD_CELL_CHANGED, self.on_mission_grid_cell_changed, self.grid_mission)
        self.Bind(wx.grid.EVT_GRID_CMD_CELL_LEFT_CLICK, self.on_mission_grid_cell_left_click, self.grid_mission)
        self.Bind(wx.grid.EVT_GRID_CMD_SELECT_CELL, self.on_mission_grid_cell_select, self.grid_mission)
        self.Bind(wx.EVT_BUTTON, self.add_wp_below_pushed, self.button_add_wp)
        self.Bind(wx.EVT_BUTTON, self.split_pushed, self.button_split)
        # end wxGlade

        #use a timer to facilitate event an event handlers for events
        #passed from another process.
        self.timer = wx.Timer(self)
        self.Bind(wx.EVT_TIMER, self.time_to_process_gui_events, self.timer)
        self.timer.Start(200)

        self.last_layout_send = time.time()
        self.Bind(wx.EVT_IDLE, self.on_idle)

        delete_br = button_renderer.ButtonRenderer("Delete",70,20)
        up_br = button_renderer.ButtonRenderer("+",20,20)
        down_br = button_renderer.ButtonRenderer("-",1,1)

        self.del_attr = wx.grid.GridCellAttr()
        self.del_attr.SetReadOnly(True)
        self.del_attr.SetRenderer(delete_br)

        self.up_attr = wx.grid.GridCellAttr()
        self.up_attr.SetReadOnly(True)
        self.up_attr.SetRenderer(up_br)

        self.down_attr = wx.grid.GridCellAttr()
        self.down_attr.SetReadOnly(True)
        self.down_attr.SetRenderer(down_br)
        self.read_only_attr = wx.grid.GridCellAttr()
        self.read_only_attr.SetReadOnly(True)

        self.grid_mission.SetColAttr(ME_DELETE_COL, self.del_attr)
        self.grid_mission.SetColAttr(ME_UP_COL, self.up_attr)
        self.grid_mission.SetColAttr(ME_DOWN_COL, self.down_attr)
        self.grid_mission.SetColAttr(ME_DIST_COL, self.read_only_attr)
        self.grid_mission.SetColAttr(ME_ANGLE_COL, self.read_only_attr)
        self.grid_mission.SetColAttr(ME_AGL_COL, self.read_only_attr)
        self.grid_mission.SetRowLabelSize(50)

        #remember what mission we opened/saved last
        self.last_mission_file_path = ""

        #remember last map click position
        self.last_map_click_pos = None

    def __set_properties(self):
        # begin wxGlade: MissionEditorFrame.__set_properties
        self.SetTitle("Mission Editor")
        self.SetSize((820, 480))
        self.label_sync_state.SetForegroundColour(wx.Colour(255, 0, 0))
        self.label_sync_state.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Droid Sans"))
        self.grid_mission.CreateGrid(0, 15)
        self.grid_mission.SetRowLabelSize(20)
        self.grid_mission.SetColLabelSize(20)
        self.grid_mission.SetColLabelValue(0, "Command")
        self.grid_mission.SetColSize(0, 150)
        self.grid_mission.SetColLabelValue(1, "P1")
        self.grid_mission.SetColLabelValue(2, "P2")
        self.grid_mission.SetColLabelValue(3, "P3")
        self.grid_mission.SetColLabelValue(4, "P4")
        self.grid_mission.SetColLabelValue(5, "Lat")
        self.grid_mission.SetColLabelValue(6, "Lon")
        self.grid_mission.SetColLabelValue(7, "Alt")
        self.grid_mission.SetColLabelValue(8, "Frame")
        self.grid_mission.SetColLabelValue(9, "Delete")
        self.grid_mission.SetColLabelValue(10, "Up")
        self.grid_mission.SetColLabelValue(11, "Down")
        self.grid_mission.SetDefaultColSize(-1)
        self.grid_mission.SetColLabelValue(12, "Distance")
        self.grid_mission.SetColLabelValue(13, "Grad (deg)")
        self.grid_mission.SetColLabelValue(14, "AGL")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MissionEditorFrame.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_top = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_top.Add(self.label_sync_state, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_top.Add((10, 0), 0, 0, 0)
        sizer_top.Add(self.button_read_wps, 0, 0, 0)
        sizer_top.Add((10, 0), 0, 0, 0)
        sizer_top.Add(self.button_write_wps, 0, 0, 0)
        sizer_top.Add((10, 0), 0, 0, 0)
        sizer_top.Add(self.button_load_wp_file, 0, 0, 0)
        sizer_top.Add((10, 0), 0, 0, 0)
        sizer_top.Add(self.button_save_wp_file, 0, 0, 0)
        sizer_3.Add(sizer_top, 0, wx.EXPAND, 0)
        sizer_3.Add(self.grid_mission, 1, wx.EXPAND, 0)
        sizer_16.Add(self.button_add_wp, 0, 0, 0)
        sizer_16.Add(self.button_split, 0, 0, 0)
        sizer_3.Add(sizer_16, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        self.Layout()
        # end wxGlade

    def set_event_queue(self, q):
        self.event_queue = q

    def set_event_queue_lock(self, l):
        self.event_queue_lock = l

    def set_gui_event_queue(self, q):
        self.gui_event_queue = q

    def set_gui_event_queue_lock(self, l):
        self.gui_event_queue_lock = l

    def set_close_window_semaphore(self, sem):
        self.close_window_semaphore = sem

    def time_to_process_gui_events(self, evt):
        event_processed = False
        queue_access_start_time = time.time()
        self.gui_event_queue_lock.acquire()
        while (not self.gui_event_queue.empty()) and (time.time() < queue_access_start_time) < 0.6:
            event_processed = True
            event = self.gui_event_queue.get()
            try:
                self.process_gui_event(event)
            except Exception as e:
                print("Caught exception (%s)" % str(e))

        self.gui_event_queue_lock.release()

        if (event_processed == True):
            #redraw window to apply changes
            self.Refresh()
            self.Update()

    def process_gui_event(self, event):
        if event.get_type() == me_event.MEGE_CLEAR_MISS_TABLE:
            self.grid_mission.ClearGrid()
            if (self.grid_mission.GetNumberRows() > 0):
                self.grid_mission.DeleteRows(0,
                        self.grid_mission.GetNumberRows())
            self.grid_mission.SetDefaultColSize(50, True)
            self.grid_mission.SetColSize(ME_COMMAND_COL, 150)
            self.grid_mission.SetColSize(ME_LAT_COL, 100)
            self.grid_mission.SetColSize(ME_LON_COL, 100)
            self.grid_mission.SetColSize(ME_ALT_COL, 75)
            self.grid_mission.SetColSize(ME_DIST_COL, 1)
            self.grid_mission.SetColSize(ME_ANGLE_COL, 1)
            self.grid_mission.SetColSize(ME_AGL_COL, 1)

            self.grid_mission.ForceRefresh()
        elif event.get_type() == me_event.MEGE_ADD_MISS_TABLE_ROWS:
            num_new_rows = event.get_arg("num_rows")
            if (num_new_rows < 1):
                return
            old_num_rows = self.grid_mission.GetNumberRows()
            self.grid_mission.AppendRows(num_new_rows)
            self.prep_new_rows(old_num_rows, num_new_rows)
            self.grid_mission.ForceRefresh()
        elif event.get_type() == me_event.MEGE_SET_MISS_ITEM:
            row = event.get_arg("num") - 1
            command = event.get_arg("command")

            if row == -1:
                #1st mission item is special: it's the immutable home position
                self.home_lat = event.get_arg("lat")
                self.home_lon = event.get_arg("lon")
                self.home_alt = event.get_arg("alt")

            else: #not the first mission item
                if command in me_defines.miss_cmds:
                    self.grid_mission.SetCellValue(row, ME_COMMAND_COL,
                            me_defines.miss_cmds[command])
                else:
                    self.grid_mission.SetCellValue(row, ME_COMMAND_COL,
                            str(command))

                self.grid_mission.SetCellValue(row, ME_P1_COL,
                        str(event.get_arg("param1")))
                self.grid_mission.SetCellValue(row, ME_P2_COL,
                        str(event.get_arg("param2")))
                self.grid_mission.SetCellValue(row, ME_P3_COL,
                        str(event.get_arg("param3")))
                self.grid_mission.SetCellValue(row, ME_P4_COL,
                        str(event.get_arg("param4")))
                self.grid_mission.SetCellValue(row, ME_LAT_COL,
                        str(event.get_arg("lat")))
                self.grid_mission.SetCellValue(row, ME_LON_COL,
                        str(event.get_arg("lon")))
                self.grid_mission.SetCellValue(row, ME_ALT_COL,
                        "%.2f" % event.get_arg("alt"))
                self.set_grad_dist()
                self.set_agl()

                frame_num = event.get_arg("frame")
                if frame_num in me_defines.frame_enum:
                    self.grid_mission.SetCellValue(row, ME_FRAME_COL,
                        me_defines.frame_enum[frame_num])
                else:
                    self.grid_mission.SetCellValue(row, ME_FRAME_COL, "Und")


        elif event.get_type() == me_event.MEGE_SET_WP_RAD:
            pass  # Widget removed
        elif event.get_type() == me_event.MEGE_SET_LOIT_RAD:
            pass  # Widget removed
        elif event.get_type() == me_event.MEGE_SET_WP_DEFAULT_ALT:
            pass  # Widget removed
        elif event.get_type() == me_event.MEGE_SET_LAST_MAP_CLICK_POS:
            self.last_map_click_pos = event.get_arg("click_pos")

    def prep_new_row(self, row_num):
        command_choices = sorted(list(me_defines.miss_cmds.values()))

        cell_ed = DropdownCellEditor(command_choices)
        self.grid_mission.SetCellEditor(row_num, ME_COMMAND_COL, cell_ed)
        cell_ed.IncRef()
        self.grid_mission.SetCellValue(row_num, ME_COMMAND_COL, "NAV_WAYPOINT")

        for i in range(1, 7):
            self.grid_mission.SetCellValue(row_num, i, "0.0")
        for i in range(12, 14):
            self.grid_mission.SetCellValue(row_num, i, "0.0")

        #set altitude to default:
        self.grid_mission.SetCellValue(row_num, ME_ALT_COL, "50.0")

        #populate frm cell editor and set to default value

        frame_cell_ed = wx.grid.GridCellChoiceEditor(list(me_defines.frame_enum.values()))
        self.grid_mission.SetCellEditor(row_num, ME_FRAME_COL, frame_cell_ed)

        # default to previous rows frame
        if row_num > 0:
            frame = self.grid_mission.GetCellValue(row_num-1, ME_FRAME_COL)
            if frame not in ["Rel", "AGL"]:
                frame = "Rel"
        else:
            frame = "Rel"
        self.grid_mission.SetCellValue(row_num, ME_FRAME_COL, frame)

        #this makes newest row always have the cursor in it,
        #making the "Add Below" button work like I want:
        self.grid_mission.SetGridCursor(row_num, ME_COMMAND_COL)

    def prep_new_rows(self, start_row, num_rows):
        num_remaining = num_rows
        current_row = start_row
        while num_remaining > 0:
            self.prep_new_row(current_row)
            current_row = current_row + 1
            num_remaining = num_remaining - 1

    def set_modified_state(self, modified):
        if (modified):
            self.set_grad_dist()
            self.set_agl()
            self.label_sync_state.SetLabel("MODIFIED")
            self.label_sync_state.SetForegroundColour(wx.Colour(255, 0, 0))
        else:
            self.label_sync_state.SetLabel("SYNCED")
            self.label_sync_state.SetForegroundColour(wx.Colour(12, 152, 26))

    def read_wp_pushed(self, event):  # wxGlade: MissionEditorFrame.<event_handler>
        self.event_queue_lock.acquire()
        self.event_queue.put(MissionEditorEvent(me_event.MEE_READ_WPS))

        #sneak in some queries about a few other items as well:
        self.event_queue.put(MissionEditorEvent(me_event.MEE_GET_WP_RAD))
        self.event_queue.put(MissionEditorEvent(me_event.MEE_GET_LOIT_RAD))
        self.event_queue.put(MissionEditorEvent(me_event.MEE_GET_WP_DEFAULT_ALT))

        self.event_queue_lock.release()
        event.Skip()

        #TODO: the read actually has to succeed before I can say this:
        self.set_modified_state(False)

    def write_wp_pushed(self, event):  # wxGlade: MissionEditorFrame.<event_handler>
        self.event_queue_lock.acquire()
        self.event_queue.put(MissionEditorEvent(me_event.MEE_WRITE_WPS,count=
            self.grid_mission.GetNumberRows()+1))

        #home point first:
        lat = self.home_lat
        lon = self.home_lon
        alt = self.home_alt
        self.event_queue.put(MissionEditorEvent(me_event.MEE_WRITE_WP_NUM,
                                                num=0,cmd_id=16,p1=0.0,p2=0.0,p3=0.0,p4=0.0,
                                                lat=lat,lon=lon,alt=alt,frame=0))

        for i in range(0, self.grid_mission.GetNumberRows()):
            cmd_id = me_defines.cmd_reverse_lookup(self.grid_mission.GetCellValue(i,0))
            #don't lock up the misseditor on missing input!
            #anything missing will just be zero
            try:
                p1 = float(self.grid_mission.GetCellValue(i,ME_P1_COL))
            except:
                p1 = 0.0
            try:
                p2 = float(self.grid_mission.GetCellValue(i,ME_P2_COL))
            except:
                p2 = 0.0
            try:
                p3 = float(self.grid_mission.GetCellValue(i,ME_P3_COL))
            except:
                p3 = 0.0
            try:
                p4 = float(self.grid_mission.GetCellValue(i,ME_P4_COL))
            except:
                p4 = 0.0
            try:
                lat = float(self.grid_mission.GetCellValue(i,ME_LAT_COL))
            except:
                lat = 0.0
            try:
                lon = float(self.grid_mission.GetCellValue(i,ME_LON_COL))
            except:
                lon = 0.0
            try:
                alt = float(self.grid_mission.GetCellValue(i,ME_ALT_COL))
            except:
                alt = 0.0
            try:
                frame = float(me_defines.frame_enum_rev[self.grid_mission.GetCellValue(i,ME_FRAME_COL)])
            except:
                frame = 0.0

            self.event_queue.put(MissionEditorEvent(me_event.MEE_WRITE_WP_NUM,
                                                    num=i+1,cmd_id=cmd_id,p1=p1,p2=p2,p3=p3,p4=p4,
                                                    lat=lat,lon=lon,alt=alt,frame=frame))

        self.event_queue_lock.release()

        self.set_modified_state(False)

        event.Skip()

    def load_wp_file_pushed(self, event):  # wxGlade: MissionEditorFrame.<event_handler>
        fd = wx.FileDialog(self, "Open Mission File", os.getcwd(), "",
                "MissionFiles(*.txt.*.wp,*.waypoints)|*.txt;*.wp;*.waypoints", wx.FD_OPEN | wx.FD_FILE_MUST_EXIST)
        if (fd.ShowModal() == wx.ID_CANCEL):
            return #user changed their mind...

        self.event_queue_lock.acquire()
        self.event_queue.put(MissionEditorEvent(me_event.MEE_LOAD_WP_FILE,
            path=fd.GetPath()))
        self.event_queue_lock.release()

        self.last_mission_file_path = fd.GetPath()

        event.Skip()

    def add_wp_below_pushed(self, event):  # wxGlade: MissionEditorFrame.<event_handler>
        row_selected = self.grid_mission.GetGridCursorRow()
        if (row_selected < 0):
            row_selected = self.grid_mission.GetNumberRows()-1

        self.grid_mission.InsertRows(row_selected+1)
        self.prep_new_row(row_selected+1)

        #set lat/lon based on last map click position:
        if self.last_map_click_pos is not None:
            self.grid_mission.SetCellValue(row_selected + 1, ME_LAT_COL,
                    str(self.last_map_click_pos[0]))
            self.grid_mission.SetCellValue(row_selected + 1, ME_LON_COL,
                    str(self.last_map_click_pos[1]))
        #highlight new row
        self.grid_mission.SelectRow(row_selected+1)
        self.set_modified_state(True)

        self.fix_jumps(row_selected+1, 1)

        event.Skip()

    def split_pushed(self, event):  # wxGlade: MissionEditorFrame.<event_handler>
        row_selected = self.grid_mission.GetGridCursorRow()
        if (row_selected < 2):
            print("Invalid row selected")
            event.Skip()
            return

        if self.grid_mission.GetCellValue(row_selected, ME_COMMAND_COL) != "NAV_WAYPOINT":
            print("Bad command (need NAV_WAYPOINT)")
            event.Skip()
            return

        if self.grid_mission.GetCellValue(row_selected-1, ME_COMMAND_COL) != "NAV_WAYPOINT":
            print("Bad previous command (need NAV_WAYPOINT)")
            event.Skip()
            return

        if (self.grid_mission.GetCellValue(row_selected, ME_FRAME_COL) !=
            self.grid_mission.GetCellValue(row_selected-1, ME_FRAME_COL)):
            print("Items differ in frame")
            event.Skip()
            return

        lat = (float(self.grid_mission.GetCellValue(row_selected, ME_LAT_COL)) +
               float(self.grid_mission.GetCellValue(row_selected-1, ME_LAT_COL)))/2
        lng = (float(self.grid_mission.GetCellValue(row_selected, ME_LON_COL)) +
               float(self.grid_mission.GetCellValue(row_selected-1, ME_LON_COL)))/2
        alt = (float(self.grid_mission.GetCellValue(row_selected, ME_ALT_COL)) +
               float(self.grid_mission.GetCellValue(row_selected-1, ME_ALT_COL)))/2
        self.grid_mission.InsertRows(row_selected)
        self.prep_new_row(row_selected)

        self.grid_mission.SetCellValue(row_selected, ME_LAT_COL, str(lat))
        self.grid_mission.SetCellValue(row_selected, ME_LON_COL, str(lng))
        self.grid_mission.SetCellValue(row_selected, ME_ALT_COL, str(alt))
        #highlight new row
        self.grid_mission.SelectRow(row_selected)
        self.set_modified_state(True)

        self.fix_jumps(row_selected, 1)

        event.Skip()

    def save_wp_file_pushed(self, event):  # wxGlade: MissionEditorFrame.<event_handler>
        fd = wx.FileDialog(self, "Save Mission File", os.getcwd(),
                           os.path.basename(self.last_mission_file_path), "MissionFiles(*.txt.*.wp,*.waypoints)|*.txt;*.wp;*.waypoints",
                               wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT)
        if (fd.ShowModal() == wx.ID_CANCEL):
            return #user change their mind...

        #ask mp_misseditor module to save file
        self.event_queue_lock.acquire()
        self.event_queue.put(MissionEditorEvent(me_event.MEE_SAVE_WP_FILE,
            path=fd.GetPath()))
        self.event_queue_lock.release()

        self.last_mission_file_path = fd.GetPath()

        event.Skip()

    def on_mission_grid_cell_select(self, event):  # wxGlade: MissionEditorFrame.<event_handler>
        self.grid_mission.SetColLabelValue(ME_P1_COL, "P1")
        self.grid_mission.SetColLabelValue(ME_P2_COL, "P2")
        self.grid_mission.SetColLabelValue(ME_P3_COL, "P3")
        self.grid_mission.SetColLabelValue(ME_P4_COL, "P4")
        self.grid_mission.SetColLabelValue(ME_LAT_COL, "Lat")
        self.grid_mission.SetColLabelValue(ME_LON_COL, "Lon")
        self.grid_mission.SetColLabelValue(ME_ALT_COL, "Alt")
        self.grid_mission.SetColLabelValue(ME_DIST_COL, "Distance")
        self.grid_mission.SetColLabelValue(ME_ANGLE_COL, "Grad (deg)")
        self.grid_mission.SetColLabelValue(ME_AGL_COL, "AGL")

        if event.GetRow() == self.grid_mission.GetNumberRows():
            # this event fires when last row is deleted; ignore
            # attempt to set a cell in that deleted row as selected.
            return
        command = self.grid_mission.GetCellValue(event.GetRow(), ME_COMMAND_COL)

        col_labels = me_defines.get_column_labels(command)
        for col in col_labels.keys():
            self.grid_mission.SetColLabelValue(col, col_labels[col])

        event.Skip()

    def on_mission_grid_cell_left_click(self, event):  # wxGlade: MissionEditorFrame.<event_handler>
        #delete column?
        if (event.GetCol() == ME_DELETE_COL):
            row = event.GetRow()
            dlg = wx.MessageDialog(self, 'Sure you want to delete item ' + str(row+1) + '?', 'Really Delete?', wx.YES_NO | wx.ICON_EXCLAMATION)
            result = dlg.ShowModal()

            if (result == wx.ID_YES):
                #delete this row
                self.grid_mission.DeleteRows(row)
                self.set_modified_state(True)
                self.fix_jumps(row, -1)
        #up column?
        elif (event.GetCol() == ME_UP_COL):
            row = event.GetRow()
            if (row == 0): #can't go any higher
                return
            #insert a copy of this row above the previous row, then delete this row
            self.grid_mission.InsertRows(row-1)
            self.prep_new_row(row-1)
            for i in range(0, self.grid_mission.GetNumberCols()):
                self.grid_mission.SetCellValue(row-1, i,
                    self.grid_mission.GetCellValue(row+1,i))
            self.grid_mission.DeleteRows(row+1)
            #move the cursor to where the row moved and highlight the row
            self.grid_mission.SetGridCursor(row-1,ME_UP_COL)
            self.grid_mission.SelectRow(row-1)

            self.set_modified_state(True)

            #Return so we don't skip the event so the cursor will go where expected
            return

        #down column?
        elif (event.GetCol() == ME_DOWN_COL):
            row = event.GetRow()
            if (row == self.grid_mission.GetNumberRows() - 1): #can't go lower
                return

            #insert a copy of this row 2 rows down, then delete this row
            self.grid_mission.InsertRows(row+2)
            self.prep_new_row(row+2)
            for i in range(0, self.grid_mission.GetNumberCols()):
                self.grid_mission.SetCellValue(row+2, i,
                    self.grid_mission.GetCellValue(row, i))
            self.grid_mission.DeleteRows(row)

            #move the cursor to where the row moved and highlight the row
            self.grid_mission.SetGridCursor(row+1,ME_DOWN_COL)
            self.grid_mission.SelectRow(row+1)

            self.set_modified_state(True)

            #Return so we don't skip the event so the cursor will go where expected
            return

        event.Skip()

    def on_mission_grid_cell_changed(self, event):  # wxGlade: MissionEditorFrame.<event_handler>
        self.set_modified_state(True)
        event.Skip()
    def on_wp_radius_changed(self, event):  # Widget removed
        pass
    def on_wp_radius_enter(self, event):  # Widget removed
        pass

    def send_loiter_rad_msg(self):  # Widget removed
        pass

    def on_loiter_rad_enter(self, event):  # Widget removed
        pass

    def on_loiter_rad_change(self, event):  # Widget removed
        pass
    def on_loiter_dir_cb_change(self, event):  # Widget removed
        pass

    def on_wp_default_alt_enter(self, event):  # Widget removed
        pass

    def on_wp_default_alt_change(self, event):  # Widget removed
        pass

    def fix_jumps(self, row_selected, delta):
        '''fix up jumps when we add/remove rows'''
        numrows = self.grid_mission.GetNumberRows()
        for row in range(numrows):
            command = self.grid_mission.GetCellValue(row, ME_COMMAND_COL)
            if command in ["DO_JUMP", "DO_CONDITION_JUMP"]:
                p1 = int(float(self.grid_mission.GetCellValue(row, ME_P1_COL)))
                if p1 > row_selected and p1+delta>0:
                    self.grid_mission.SetCellValue(row, ME_P1_COL, str(float(p1+delta)))

    def has_location_cmd(self, cmd_id):
        '''return True if a WP command has a location'''
        if isinstance(cmd_id, str):
            cmd_id = eval(f"mavutil.mavlink.MAV_CMD_{cmd_id}")
        if cmd_id in mavutil.mavlink.enums['MAV_CMD'].keys():
            cmd_enum = mavutil.mavlink.enums['MAV_CMD'][cmd_id]
            # default to having location for older installs of pymavlink
            # which don't have the attribute
            return getattr(cmd_enum,'has_location',True)
        return False

    def has_location(self, lat, lon, cmd_id):
        '''return True if a WP command has a location'''
        if lat == 0 and lon == 0:
            return False
        return self.has_location_cmd(cmd_id)

    def set_grad_dist(self):
        '''fix up distance and gradient when changing cell values'''
        home_def_alt = self.home_alt
        numrows = self.grid_mission.GetNumberRows()
        for row in range(1,numrows):
            command = self.grid_mission.GetCellValue(row, ME_COMMAND_COL)
            command_prev = self.grid_mission.GetCellValue(row - 1, ME_COMMAND_COL)
            lat = float(self.grid_mission.GetCellValue(row, ME_LAT_COL))
            lon = float(self.grid_mission.GetCellValue(row, ME_LON_COL))
            if not self.has_location(lat, lon, command):
                dist = 0.0
                grad = 0.0
            else :
              if "NAV" in command:
                row_prev = row - 1
                while not self.has_location_cmd(command_prev) and (row_prev > 0):
                    command_prev = self.grid_mission.GetCellValue(row_prev - 1, ME_COMMAND_COL)
                    row_prev = row_prev - 1
                prev_lat = float(self.grid_mission.GetCellValue(row_prev, ME_LAT_COL))
                prev_lon = float(self.grid_mission.GetCellValue(row_prev, ME_LON_COL))
                prev_alt = float(self.grid_mission.GetCellValue(row_prev, ME_ALT_COL))
                if (self.grid_mission.GetCellValue(row_prev, ME_FRAME_COL) == "Rel"):
                    prev_alt = prev_alt + home_def_alt
                elif (self.grid_mission.GetCellValue(row_prev, ME_FRAME_COL) == "AGL"):
                    prev_alt = self.ElevationModel.GetElevation(prev_lat, prev_lon) + prev_alt
                while not self.has_location(prev_lat,prev_lon,command_prev) and (row_prev > 0):
                    prev_lat = float(self.grid_mission.GetCellValue(row_prev - 1, ME_LAT_COL))
                    prev_lon = float(self.grid_mission.GetCellValue(row_prev - 1, ME_LON_COL))
                    command_prev = self.grid_mission.GetCellValue(row_prev - 1, ME_COMMAND_COL)
                    row_prev = row_prev - 1
                dist = mp_util.gps_distance(lat, lon, prev_lat, prev_lon)
                curr_alt = float(self.grid_mission.GetCellValue(row, ME_ALT_COL))
                if (self.grid_mission.GetCellValue(row, ME_FRAME_COL) == "Rel"):
                    curr_alt = curr_alt + home_def_alt
                elif(self.grid_mission.GetCellValue(row, ME_FRAME_COL) == "AGL"):
                    curr_alt = curr_alt + self.ElevationModel.GetElevation(lat, lon)
                grad = math.atan2(curr_alt - prev_alt, dist) *180 / math.pi
              else:
                grad = 0.0
                dist = 0.0
            dist = format(dist, '.1f')
            grad = format(grad, '.1f')
            self.grid_mission.SetCellValue(row, ME_DIST_COL, str(dist))
            self.grid_mission.SetCellValue(row, ME_ANGLE_COL, str(grad))
            
    def set_agl(self):
        '''update agl altitude when changing cell values'''
        home_def_alt = self.home_alt
        numrows = self.grid_mission.GetNumberRows()
        for row in range(0,numrows):
            command = self.grid_mission.GetCellValue(row, ME_COMMAND_COL)
            lat = float(self.grid_mission.GetCellValue(row, ME_LAT_COL))
            lon = float(self.grid_mission.GetCellValue(row, ME_LON_COL))
            agl = 0.0
            elevation = self.ElevationModel.GetElevation(lat, lon)
            if elevation == None:
                continue
            if self.has_location(lat, lon, command) and "NAV" in command:
                agl = float(self.grid_mission.GetCellValue(row, ME_ALT_COL))
                frame = self.grid_mission.GetCellValue(row, ME_FRAME_COL)
                if frame == "Rel":
                    agl = agl + home_def_alt - elevation
                elif self.grid_mission.GetCellValue(row, ME_FRAME_COL) == "Abs":
                    agl = agl - elevation
            else:
                continue
            agl = format(float(agl), '.1f')
            self.grid_mission.SetCellValue(row, ME_AGL_COL, agl)

    def on_idle(self, event):
        now = time.time()
        if now - self.last_layout_send > 1:
            self.last_layout_send = now
            self.event_queue.put(win_layout.get_wx_window_layout(self))

        obj = None
        while not self.state.object_queue.empty():
            obj = self.state.object_queue.get()
            if isinstance(obj, win_layout.WinLayout):
                win_layout.set_wx_window_layout(self, obj)

# end of class MissionEditorFrame
if __name__ == "__main__":
    app = wx.App(False)
    wx.InitAllImageHandlers()
    missionEditor = (None, wx.ID_ANY, "")
    app.SetTopWindow(missionEditor)
    missionEditor.Show()
    app.MainLoop()
